view: demo_test_attribute_pivot_table {
sql_table_name: TEST_ATTRIBUTE_PIVOT_TABLE ;;

# Auto-generated by CDP Internal API
# If you wish to customize/extend this lookML, please use LookML Refinements : https://docs.looker.com/data-modeling/learning-lookml/refinements


dimension: dataset_instance_id {
type: number
sql: ${TABLE}.dataset_instance_id ;;
}


dimension: master_digital_profile_id {
type: string
sql: ${TABLE}.master_digital_profile_id ;;
}


dimension: attr1 {
type: string
sql: ${TABLE}.attr1 ;;
}


dimension: attr2 {
type: string
sql: ${TABLE}.attr2 ;;
}


dimension: attr3 {
type: string
sql: ${TABLE}.attr3 ;;
}


dimension: attr4 {
type: string
sql: ${TABLE}.attr4 ;;
}


dimension: attr5 {
type: string
sql: ${TABLE}.attr5 ;;
}


dimension: attr6 {
type: string
sql: ${TABLE}.attr6 ;;
}


dimension: attr7 {
type: string
sql: ${TABLE}.attr7 ;;
}


dimension: attr8 {
type: string
sql: ${TABLE}.attr8 ;;
}


dimension: attr9 {
type: string
sql: ${TABLE}.attr9 ;;
}


dimension: attr10 {
type: string
sql: ${TABLE}.attr10 ;;
}


dimension: attr11 {
type: string
sql: ${TABLE}.attr11 ;;
}


dimension: attr12 {
type: string
sql: ${TABLE}.attr12 ;;
}


dimension: attr13 {
type: string
sql: ${TABLE}.attr13 ;;
}



measure: count {
type: count
}
}