view: demo_vw_allpagesvisited {
sql_table_name: VW_ALLPAGESVISITED ;;

# Auto-generated by CDP Internal API
# If you wish to customize/extend this lookML, please use LookML Refinements : https://docs.looker.com/data-modeling/learning-lookml/refinements


dimension: hubspot_cookie {
type: string
sql: ${TABLE}.hubspot_cookie ;;
}


dimension: mcvisid {
type: string
sql: ${TABLE}.mcvisid ;;
}


dimension: pagename {
type: string
sql: ${TABLE}.pagename ;;
}



measure: count {
type: count
}
}