view: demo_vw_crm_vid_mdpid_mapping {
sql_table_name: VW_CRM_VID_MDPID_MAPPING ;;

# Auto-generated by CDP Internal API
# If you wish to customize/extend this lookML, please use LookML Refinements : https://docs.looker.com/data-modeling/learning-lookml/refinements


dimension: vid {
type: number
sql: ${TABLE}.vid ;;
}


dimension: master_digital_profile_id {
type: number
sql: ${TABLE}.master_digital_profile_id ;;
}



measure: count {
type: count
}
}