view: demo_vw_mdpid_utk_mapping {
sql_table_name: VW_MDPID_UTK_MAPPING ;;

# Auto-generated by CDP Internal API
# If you wish to customize/extend this lookML, please use LookML Refinements : https://docs.looker.com/data-modeling/learning-lookml/refinements


dimension: hubspot_cookie {
type: string
sql: ${TABLE}.hubspot_cookie ;;
}


dimension: master_digital_profile_id {
type: string
sql: ${TABLE}.master_digital_profile_id ;;
}



measure: count {
type: count
}
}