view: demo_vw_neustar_cif_mdpid_mapping {
sql_table_name: VW_NEUSTAR_CIF_MDPID_MAPPING ;;

# Auto-generated by CDP Internal API
# If you wish to customize/extend this lookML, please use LookML Refinements : https://docs.looker.com/data-modeling/learning-lookml/refinements


dimension: master_digital_profile_id {
type: number
sql: ${TABLE}.master_digital_profile_id ;;
}


dimension: individual_key {
type: number
sql: ${TABLE}.individual_key ;;
}



measure: count {
type: count
}
}